test:
  primary:
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] + "/auth_by_primary" %>
    pool: <%= ENV["DB_POOL_SIZE"] || 5 %>
  statistics:
    encoding: unicode
    url: <%= ENV["TIMESCALE_URL"] + "/auth_by_statistics" %>
    pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
