production: &production
  project: modular-rails
  bucket: modular-rails-web-production
  project_id: modular-rails
  client_email: buckets-user@modular-rails.iam.gserviceaccount.com
  client_id: "0000000000000"
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/buckets-user%40modular-rails.iam.gserviceaccount.com

staging:
  <<: *production
  bucket: modular-rails-web-staging
